# Simple workflow for deploying static content to GitHub Pages
# https://vite.dev/guide/static-deploy
name: Deploy static content to development environment

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['development']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

# This execute all process to deploy the page 
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.deployment.outputs.page_url }}development
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create .env file
      
        # Run Example
        # echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        # echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        # echo "PORT=${{ vars.PORT }}" >> .env
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env
        

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # Upload dist folder
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5